apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcbans-main-cronjob
  namespace: mcbans
spec:
  schedule: "*/5 * * * *"  # Run every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mcbans-main
            image: ghcr.io/mcbans/mcbans-main:${VERSION}
            # You can override the default CMD by uncommenting and modifying the following:
            args: ["${API_KEY}"]
            env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
          restartPolicy: Never
      backoffLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcbans-bantest-cronjob
  namespace: mcbans
spec:
  schedule: "*/5 * * * *"  # Run every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mcbans-bantest
            image: ghcr.io/mcbans/mcbans-bantest:${VERSION}
            # You can override the default CMD by uncommenting and modifying the following:
            args: ["${API_KEY}", "${PLAYER_TO_BAN}"]
            env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
          restartPolicy: Never
      backoffLimit: 3
