apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcbans-main-cronjob
  namespace: mcbans
spec:
  schedule: "*/5 * * * *"  # Run every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mcbans-main
            image: ghcr.io/mcbans/mcbans-main:${VERSION}
            env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
            - name: OVERRIDE_API
              value: 50.115.119.30
            - name: OVERRIDE_PORT
              value: "8082"
            - name: MCBANS_API_KEY
              value: "${API_KEY}"
          restartPolicy: Never
      backoffLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mcbans-bantest-cronjob
  namespace: mcbans
spec:
  schedule: "*/5 * * * *"  # Run every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mcbans-bantest
            image: ghcr.io/mcbans/mcbans-bantest:${VERSION}
            env:
            - name: JAVA_OPTS
              value: "-Xmx512m"
            - name: OVERRIDE_API
              value: 50.115.119.30
            - name: OVERRIDE_PORT
              value: "8082"
            - name: MCBANS_API_KEY
              value: "${API_KEY}"
            - name: MCBANS_PLAYER_TO_BAN
              value: "${PLAYER_TO_BAN}"
          restartPolicy: Never
      backoffLimit: 3
