##  Plugin Information  ##
name: MCBans
main: com.mcbans.plugin.MCBans
version: 4.5.1
api-version: 1.18
description: A global banning solution
website: http://mcbans.com/
softdepend: [LogBlock, HawkEye, CoreProtect, Vault, PermissionsEx]
author: Firestar
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername|UUID> [reason]
    permission: mcbans.kick
  ban:
    description: ban a user
    usage: /<command> <playername|UUID> [-g/-t/reason] [reason]
    permission: mcbans.ban.*
  globalban:
    description: global bans a user
    aliases: [gban]
    usage: /<command> <playername|UUID> [reason]
    permission: mcbans.ban.global
  rban:
    description: roll back bans
    usage: /<command> <playername|UUID> [-g/-t/reason] [reason]
    permission: mcbans.ban.rollback
  namelookup:
    description: history of a players UUID
    aliases: [nlup]
    usage: /<command> <playername|UUID>
    permission: mcbans.lookup.player
  unban:
    description: unban a user
    usage: /<command> <playername|UUID>
    permission: mcbans.unban
  tempban:
    description: temporary ban user
    aliases: [tban]
    usage: /<command> <playername|UUID> <duration> <m(minutes) or h(hours) or d(days) or w(weeks)> [reason]
    permission: mcbans.ban.temp
  banip:
    description: bans an IP address
    aliases: [ipban]
    usage: /<command> <ip> [reason]
    permission: mcbans.ban.ip
  lookup:
    description: lookup a player information
    aliases: [lup]
    usage: /<command> <playername|UUID>
    permission: mcbans.lookup.player
  banlookup:
    description: lookup a ban information
    aliases: [blup]
    usage: /<command> <banID>
    permission: mcbans.lookup.ban
  altlookup:
    description: lookup a player alt accounts
    aliases: [alup, alt]
    usage: /<command> <playername|UUID>
    permission: mcbans.lookup.alt
  mcbans:
    description: mcbans functions
    usage: /<command> <function>
    permission: mcbans.admin
  mcbs:
    description: mcbans server settings
    usage: /<command> <setting> <value>
    permission: mcbans.admin
permissions:
  mcbans.announce:
    description: Announces bans and kicks to anyone with this permission
    default: op
  mcbans.admin:
    description: Admin privileges to mcbans, access to admin commands
    default: op
  mcbans.ban.global:
    description: Permission to use global ban command
    default: op
  mcbans.ban.local:
    description: Permission to use local ban command
    default: op
  mcbans.ban.temp:
    description: Permission to use temp ban command
    default: op
  mcbans.ban.rollback:
    description: Gives rban commands
    default: op
  mcbans.ban.ip:
    description: Gives banip command
    default: op
  mcbans.ban.exempt:
    description: Permission to exempt from bans
    default: op
  mcbans.unban:
    description: Permission to use unban command
    default: op
  mcbans.view.bans:
    description: View ban information on user joining
    default: op
  mcbans.view.alts:
    description: show notification of a players alts on connect
    default: op
  mcbans.view.previous:
    description: show notification of a players previous names on connect
    default: op
  mcbans.view.proxy:
    description: show notification of a players using proxies on connect
    default: op
  mcbans.view.staff:
    description: show notification of a mcbans staff on connect
    default: true
  mcbans.hideview:
    description: Hide notification of previous bans/alts on connect
    default: false
  mcbans.kick:
    description: Permission to use kick command
    default: op
  mcbans.kick.exempt:
    description: Permission to exempt from kicks
    default: op
  mcbans.lookup.player:
    description: Permission to use lookup command
    default: op
  mcbans.lookup.ban:
    description: Permission to use banlookup command
    default: op
  mcbans.lookup.alt:
    description: Permission to use altlookup command
    default: op
