# English MCBans File, Translated By: __

unBanSuccess: "%PLAYER% has been unbanned!"
unBanError: "Error removing the ban for %PLAYER%!"
unBanGroup: "%PLAYER% banned from a server in the same group as you!"
unBanNot: "%PLAYER% was not banned!"

banExemptPlayer: "%PLAYER% has ban exempt permission!"

localBanPlayer: "You have been banned, check MCBans.com!"
localBanSuccess: "%PLAYER% has been banned [%REASON%]"
localBanError: "Error adding ban for %PLAYER%!"
localBanGroup: "%PLAYER% banned from a server in the same group as you!"
localBanAlready: "%PLAYER% is already banned from this server!"

globalBanPlayer: "You have been banned, check MCBans.com!"
globalBanSuccess: "%PLAYER% has been banned [%REASON%]"
globalBanError: "Error adding ban for %PLAYER%!"
globalBanWarning: "Error banning %PLAYER%! Reason contained badword: %BADWORD%"
globalBanGroup: "%PLAYER% banned from a server in the same group as you!"
globalBanAlready: "%PLAYER% is already banned from this server!"

tempBanPlayer: "%REASON%"
tempBanSuccess: "%PLAYER% has been temporarily banned [%REASON%]"
tempBanError: "Error adding ban for %PLAYER%!"
tempBanGroup: "%PLAYER% banned from a server in the same group as you!"
tempBanAlready: "%PLAYER% is already banned from this server!"

kickPlayer: "%REASON%"
kickSuccess: "%PLAYER% has been kicked!"
kickNoPlayer: "%PLAYER% is not online!"
kickExemptPlayer: "%PLAYER% has kick exempt permission!"
kickBroadcast: "%ADMIN% has kicked %PLAYER% \\n%REASON%"

ipBanSuccess: "IP %IP% has been banned [%REASON%]"
ipBanError: "Error adding ban for IP %IP%!"
ipBanAlready: "IP %IP% is already banned from this server!"

formatError: "Incorrect parameters!"
invalidName: "Invalid player name!"
invalidIP: "Invalid IP address!"
invalidNameOrIP: "Invalid player name or IP address!"
permissionDenied: "Permission denied!"
rbMethodNotFound: "Rollback plugin not found!"
unavailable: "MCBans service unavailable! Please try again later!"
underMinRep: "Your reputation is below this servers threshold!"
overMaxAlts: "You have more alt accounts than this server allows!"
altBanned: "You have an alt account banned from this server!"
altAccounts: "%PLAYER% may have alt accounts [ %ALTS% ]!"
disputes: "You have %COUNT% open dispute(s)!"
previousBans: "%PLAYER% has previous bans!"
bansOnRecord: "You have bans on record! ( check http://mcbans.com )"
isMCBansMod: "%PLAYER% is an MCBans.com Staff Member!"
banReturnMessage: "&EReason: &C%REASON%\n&EBan from: &F%ADMIN%\n&EBan Type: &7%TYPE%\n&Bhttp://mcbans.com/ban/%BANID%"
successSetting: "Successfully changed setting [%REASON%]!"
failSetting: "Failed to change setting [%REASON%]!"

previousNames: '%PLAYER% has changed their name within the last 2 months "%PLAYERS%"'
previousNamesHas: '%PLAYER% has recently changed their name from "%PLAYERS%"!'
previousNamesNone: "%PLAYER% has no name changes on record."

proxyDetected: "%PLAYER% is using a proxy %REASON%"