name: mcbans
main: com.mcbans.firestar.mcbans.bukkitInterface
version: 3.0p
author: Firestar
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days)> [reason]
  lookup:
    description: lookup a player
    usage: /<command> <playername>
  lup:
    description: alias of lookup
    usage: /<command> <playername>
  mcbans:
    description: player set
    usage: /<command> <playername>
  inbox:
    description: check your inbox
    aliases: [binbox]
    usage: /<command>
  read:
    description: read a message
    aliases: [bread]
    usage: /<command> [messageID]
  send:
    description: send a messsage
    aliases: [bsend]
    usage: /<command> <playername> <message>
  block:
    description: player set
    aliases: [bblock]
    usage: /<command> <playername>
  unblock:
    description: player set
    aliases: [bunblock]
    usage: /<command> <playername>
  lbev:
    description: player set
    usage: /<command> <playername>