name: mcbans
main: com.mcbans.firestar.mcbans.bukkitInterface
version: 3.0
author: Firestar
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days)> [reason]
  lookup:
    description: lookup a player
    usage: /<command> <playername>
  lup:
    description: alias of lookup
    usage: /<command> <playername>
  mcbans:
    description: player set
    usage: /<command> <playername>
permissions:
  mcbans.ban.view:
    description: View ban information on user joining
    default: op
  mcbans.ban.global:
    description: Give global bans
    default: op
  mcbans.ban.local:
    description: Give local bans
    default: op
  mcbans.ban.temp:
    description: Give temp bans
    default: op
  mcbans.unban:
    description: Unban users
    default: op
  mcbans.lookup:
    description: Lookup ban history on command
    default: op
  mcbans.kick:
    description: Kick users
    default: op
  mcbans.mode:
    description: Change between online and offline modes
    default: op
  mcbans.all:
    description: All permissions
    children:
      mcbans.ban.view: true
      mcbans.ban.global: true
      mcbans.ban.local: true
      mcbans.ban.temp: true
      mcbans.unban: true
      mcbans.lookup: true
      mcbans.kick: true
      mcbans.mode: true