##  Plugin Information  ##
name: MCBans
main: com.mcbans.firestar.mcbans.MCBans
version: 4.21
description: A global banning solution
website: http://mcbans.com/
softdepend: [NoCheatPlus, AntiCheat, LogBlock, HawkEye, CoreProtect, Vault, PermissionsEx]
author: Firestar, Syamn
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/t/reason] [reason]
  globalban:
    description: global bans a user
    aliases: [gban]
    usage: /<command> <playername> [reason]
  rban:
    description: roll back bans
    usage: /<command> <playername> [g/t/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    aliases: [tban]
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days) or w(weeks)> [reason]
  banip:
    description: bans an IP address
    aliases: [ipban]
    usage: /<command> <ip> [reason]
  lookup:
    description: lookup a player information
    aliases: [lup]
    usage: /<command> <playername>
  banlookup:
    description: lookup a ban information
    aliases: [blup]
    usage: /<command> <banID>
  altlookup:
    description: lookup a player alt accounts
    aliases: [alup, alt]
    usage: /<command> <playername>
  mcbans:
    description: mcbans functions
    usage: /<command> <function>
permissions:
  mcbans.admin:
    description: Admin privileges to mcbans, access to admin commands
    default: op
  mcbans.ban.global:
    description: Permission to use global ban command
    default: op
  mcbans.ban.local:
    description: Permission to use local ban command
    default: op
  mcbans.ban.temp:
    description: Permission to use temp ban command
    default: op
  mcbans.ban.rollback:
    description: Gives rban commands
    default: op
  mcbans.ban.ip:
    description: Gives banip command
    default: op
  mcbans.unban:
    description: Permission to use unban command
    default: op
  mcbans.view.bans:
    description: View ban information on user joining
    default: op
  mcbans.view.alts:
    description: show notification of a players alts on connect
    default: op
  mcbans.view.staff:
    description: show notification of a mcbans staff on connect
    default: true
  mcbans.hideview:
    description: Hide notification of previous bans/alts on connect
    default: false
  mcbans.kick:
    description: Permission to use kick command
    default: op
  mcbans.kick.exempt:
    description: Permission to exempt from kicks
    default: op
  mcbans.lookup.player:
    description: Permission to use lookup command
    default: op
  mcbans.lookup.ban:
    description: Permission to use banlookup command
    default: op
  mcbans.lookup.alt:
    description: Permission to use altlookup command
    default: op
