##  Plugin Information  ##
name: MCBans
main: com.mcbans.firestar.mcbans.BukkitInterface
version: 3.9
description: A global banning solution
website: http://mcbans.com/
softdepend: [NoCheatPlus, AntiCheat, LogBlock, HawkEye, CoreProtect, Vault, PermissionsEx]
author: Firestar, Syamn, bands96
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/t/reason] [reason]
  gban:
    description: global bans a user
    usage: /<command> <playername> [reason]
  rban:
    description: roll back bans
    usage: /<command> <playername> [g/t/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    aliases: [tban]
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days)> [reason]
  lookup:
    description: lookup a player
    aliases: [lup]
    usage: /<command> <playername>
  mcbans:
    description: mcbans functions
    usage: /<command> <function>
permissions:
  mcbans.admin:
    description: Admin privileges to mcbans, access to admin commands
    default: op
  mcbans.ban.global:
    description: Permission to use global ban command
    default: op
  mcbans.ban.local:
    description: Permission to use local ban command
    default: op
  mcbans.ban.temp:
    description: Permission to use temp ban command
    default: op
  mcbans.ban.rollback:
    description: Gives rban commands
    default: op
  mcbans.unban:
    description: Permission to use unban command
    default: op
  mcbans.view.bans:
    description: View ban information on user joining
    default: op
  mcbans.view.alts:
    description: show notification of a players alts on connect
    default: op
  mcbans.alts.hide:
    description: Hide notification of alts on connect
    default: op
  mcbans.kick:
    description: Permission to use kick command
    default: op
  mcbans.lookup:
    description: Permission to use lookup command
    default: op