name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Extract version from build.gradle
        id: gradle_version
        run: |
          VERSION=$(grep -m 1 "version" build.gradle | awk -F "'" '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Main Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.main
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mcbans-main:latest
            ghcr.io/${{ github.repository_owner }}/mcbans-main:${{ env.VERSION }}

      - name: Build and push BanTest Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.bantest
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mcbans-bantest:latest
            ghcr.io/${{ github.repository_owner }}/mcbans-bantest:${{ env.VERSION }}
